"""default false added

Revision ID: 85130b4aa6b4
Revises: 9497d3147dd6
Create Date: 2024-10-03 19:08:04.388201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85130b4aa6b4'
down_revision: Union[str, None] = '9497d3147dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_otp'), 'users', ['otp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_otp'), table_name='users')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
