"""default false added

Revision ID: 9497d3147dd6
Revises: bcfab1052c7a
Create Date: 2024-09-25 13:29:27.816285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9497d3147dd6'
down_revision: Union[str, None] = 'bcfab1052c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_reference_token'), 'users', ['reference_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reference_token'), table_name='users')
    # ### end Alembic commands ###
